// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login.proto

/*
Package pto is a generated protocol buffer package.

It is generated from these files:
	login.proto

It has these top-level messages:
	SLogin
	CLogin
	SLoginReq
	CLoginRet
*/
package pto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SLogin struct {
	Ver     string `protobuf:"bytes,1,opt,name=ver" json:"ver,omitempty"`
	Account string `protobuf:"bytes,2,opt,name=account" json:"account,omitempty"`
	Passwd  string `protobuf:"bytes,3,opt,name=passwd" json:"passwd,omitempty"`
}

func (m *SLogin) Reset()                    { *m = SLogin{} }
func (m *SLogin) String() string            { return proto.CompactTextString(m) }
func (*SLogin) ProtoMessage()               {}
func (*SLogin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SLogin) GetVer() string {
	if m != nil {
		return m.Ver
	}
	return ""
}

func (m *SLogin) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *SLogin) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

type CLogin struct {
	Uid int64 `protobuf:"varint,2,opt,name=uid" json:"uid,omitempty"`
}

func (m *CLogin) Reset()                    { *m = CLogin{} }
func (m *CLogin) String() string            { return proto.CompactTextString(m) }
func (*CLogin) ProtoMessage()               {}
func (*CLogin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CLogin) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type SLoginReq struct {
	Uid int64 `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
}

func (m *SLoginReq) Reset()                    { *m = SLoginReq{} }
func (m *SLoginReq) String() string            { return proto.CompactTextString(m) }
func (*SLoginReq) ProtoMessage()               {}
func (*SLoginReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SLoginReq) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type CLoginRet struct {
	RoleUid []int32 `protobuf:"varint,1,rep,packed,name=role_uid,json=roleUid" json:"role_uid,omitempty"`
	RoleCid []int32 `protobuf:"varint,2,rep,packed,name=role_cid,json=roleCid" json:"role_cid,omitempty"`
}

func (m *CLoginRet) Reset()                    { *m = CLoginRet{} }
func (m *CLoginRet) String() string            { return proto.CompactTextString(m) }
func (*CLoginRet) ProtoMessage()               {}
func (*CLoginRet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CLoginRet) GetRoleUid() []int32 {
	if m != nil {
		return m.RoleUid
	}
	return nil
}

func (m *CLoginRet) GetRoleCid() []int32 {
	if m != nil {
		return m.RoleCid
	}
	return nil
}

func init() {
	proto.RegisterType((*SLogin)(nil), "pto.s_login")
	proto.RegisterType((*CLogin)(nil), "pto.c_login")
	proto.RegisterType((*SLoginReq)(nil), "pto.s_login_req")
	proto.RegisterType((*CLoginRet)(nil), "pto.c_login_ret")
}

func init() { proto.RegisterFile("login.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 172 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0xc9, 0x4f, 0xcf,
	0xcc, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2e, 0x28, 0xc9, 0x57, 0xf2, 0xe5, 0x62,
	0x2f, 0x8e, 0x07, 0x8b, 0x0a, 0x09, 0x70, 0x31, 0x97, 0xa5, 0x16, 0x49, 0x30, 0x2a, 0x30, 0x6a,
	0x70, 0x06, 0x81, 0x98, 0x42, 0x12, 0x5c, 0xec, 0x89, 0xc9, 0xc9, 0xf9, 0xa5, 0x79, 0x25, 0x12,
	0x4c, 0x60, 0x51, 0x18, 0x57, 0x48, 0x8c, 0x8b, 0xad, 0x20, 0xb1, 0xb8, 0xb8, 0x3c, 0x45, 0x82,
	0x19, 0x2c, 0x01, 0xe5, 0x29, 0x49, 0x73, 0xb1, 0x27, 0x23, 0x8c, 0x2b, 0xcd, 0x4c, 0x01, 0x6b,
	0x64, 0x0e, 0x02, 0x31, 0x95, 0xe4, 0xb9, 0xb8, 0xa1, 0x76, 0xc5, 0x17, 0xa5, 0x16, 0xc2, 0x14,
	0x30, 0x22, 0x14, 0x38, 0x73, 0x71, 0x27, 0xc3, 0x15, 0x94, 0x08, 0x49, 0x72, 0x71, 0x14, 0xe5,
	0xe7, 0xa4, 0xc6, 0x43, 0x54, 0x31, 0x6b, 0xb0, 0x06, 0xb1, 0x83, 0xf8, 0xa1, 0x99, 0x29, 0x70,
	0xa9, 0x64, 0xb0, 0x0d, 0x70, 0x29, 0xe7, 0xcc, 0x94, 0x24, 0x36, 0xb0, 0xef, 0x8c, 0x01, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x12, 0x56, 0xc0, 0x29, 0xec, 0x00, 0x00, 0x00,
}
